// src/components/react/counter.gen.tsx
/** @jsxImportSource react */
import COUNTER0 from './counter/counter0'
import COUNTER1 from './counter/counter1'
import COUNTER2 from './counter/counter2'
import COUNTER3 from './counter/counter3'
import COUNTER4 from './counter/counter4'
import COUNTER5 from './counter/counter5'
import COUNTER6 from './counter/counter6'
import COUNTER7 from './counter/counter7'
import COUNTER8 from './counter/counter8'
import COUNTER9 from './counter/counter9'
import COUNTER10 from './counter/counter10'
import COUNTER11 from './counter/counter11'
import COUNTER12 from './counter/counter12'
import COUNTER13 from './counter/counter13'
import COUNTER14 from './counter/counter14'
import COUNTER15 from './counter/counter15'
import COUNTER16 from './counter/counter16'
import COUNTER17 from './counter/counter17'
import COUNTER18 from './counter/counter18'
import COUNTER19 from './counter/counter19'
import COUNTER20 from './counter/counter20'
import COUNTER21 from './counter/counter21'
import COUNTER22 from './counter/counter22'
import COUNTER23 from './counter/counter23'
import COUNTER24 from './counter/counter24'
import COUNTER25 from './counter/counter25'
import COUNTER26 from './counter/counter26'
import COUNTER27 from './counter/counter27'
import COUNTER28 from './counter/counter28'
import COUNTER29 from './counter/counter29'
import COUNTER30 from './counter/counter30'
import COUNTER31 from './counter/counter31'
import COUNTER32 from './counter/counter32'
import COUNTER33 from './counter/counter33'
import COUNTER34 from './counter/counter34'
import COUNTER35 from './counter/counter35'
import COUNTER36 from './counter/counter36'
import COUNTER37 from './counter/counter37'
import COUNTER38 from './counter/counter38'
import COUNTER39 from './counter/counter39'
import COUNTER40 from './counter/counter40'
import COUNTER41 from './counter/counter41'
import COUNTER42 from './counter/counter42'
import COUNTER43 from './counter/counter43'
import COUNTER44 from './counter/counter44'
import COUNTER45 from './counter/counter45'
import COUNTER46 from './counter/counter46'
import COUNTER47 from './counter/counter47'
import COUNTER48 from './counter/counter48'
import COUNTER49 from './counter/counter49'

export default (props: { initialValue: number, maxValue: number, recurse: boolean }) => <>
  <COUNTER0 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER1 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER2 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER3 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER4 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER5 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER6 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER7 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER8 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER9 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER10 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER11 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER12 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER13 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER14 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER15 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER16 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER17 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER18 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER19 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER20 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER21 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER22 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER23 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER24 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER25 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER26 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER27 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER28 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER29 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER30 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER31 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER32 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER33 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER34 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER35 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER36 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER37 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER38 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER39 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER40 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER41 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER42 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER43 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER44 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER45 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER46 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER47 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER48 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER49 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
</>

// src/components/qwik/counter.gen.tsx
/** @jsxImportSource @builder.io/qwik */
import { component$ } from '@builder.io/qwik'
import COUNTER0 from './counter/counter0'
import COUNTER1 from './counter/counter1'
import COUNTER2 from './counter/counter2'
import COUNTER3 from './counter/counter3'
import COUNTER4 from './counter/counter4'
import COUNTER5 from './counter/counter5'
import COUNTER6 from './counter/counter6'
import COUNTER7 from './counter/counter7'
import COUNTER8 from './counter/counter8'
import COUNTER9 from './counter/counter9'
import COUNTER10 from './counter/counter10'
import COUNTER11 from './counter/counter11'
import COUNTER12 from './counter/counter12'
import COUNTER13 from './counter/counter13'
import COUNTER14 from './counter/counter14'
import COUNTER15 from './counter/counter15'
import COUNTER16 from './counter/counter16'
import COUNTER17 from './counter/counter17'
import COUNTER18 from './counter/counter18'
import COUNTER19 from './counter/counter19'
import COUNTER20 from './counter/counter20'
import COUNTER21 from './counter/counter21'
import COUNTER22 from './counter/counter22'
import COUNTER23 from './counter/counter23'
import COUNTER24 from './counter/counter24'
import COUNTER25 from './counter/counter25'
import COUNTER26 from './counter/counter26'
import COUNTER27 from './counter/counter27'
import COUNTER28 from './counter/counter28'
import COUNTER29 from './counter/counter29'
import COUNTER30 from './counter/counter30'
import COUNTER31 from './counter/counter31'
import COUNTER32 from './counter/counter32'
import COUNTER33 from './counter/counter33'
import COUNTER34 from './counter/counter34'
import COUNTER35 from './counter/counter35'
import COUNTER36 from './counter/counter36'
import COUNTER37 from './counter/counter37'
import COUNTER38 from './counter/counter38'
import COUNTER39 from './counter/counter39'
import COUNTER40 from './counter/counter40'
import COUNTER41 from './counter/counter41'
import COUNTER42 from './counter/counter42'
import COUNTER43 from './counter/counter43'
import COUNTER44 from './counter/counter44'
import COUNTER45 from './counter/counter45'
import COUNTER46 from './counter/counter46'
import COUNTER47 from './counter/counter47'
import COUNTER48 from './counter/counter48'
import COUNTER49 from './counter/counter49'

export default component$((props: { initialValue: number, maxValue: number, recurse: boolean }) => <>
  <COUNTER0 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER1 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER2 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER3 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER4 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER5 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER6 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER7 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER8 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER9 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER10 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER11 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER12 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER13 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER14 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER15 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER16 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER17 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER18 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER19 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER20 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER21 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER22 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER23 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER24 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER25 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER26 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER27 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER28 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER29 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER30 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER31 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER32 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER33 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER34 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER35 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER36 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER37 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER38 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER39 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER40 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER41 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER42 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER43 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER44 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER45 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER46 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER47 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER48 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
<COUNTER49 initialValue={props.initialValue} maxValue={props.maxValue} recurse={props.recurse} />
</>)
