// src/components/react/counter.tsx
/** @jsxImportSource react */
import { useState } from 'react'
import Button from './button'
import './counter.css'
import Gauge from "./gauge"

export default function Counter(props: { initialValue: number, maxValue: number, recurse: boolean }) {
  const [count, setCount] = useState(props.initialValue)
  function add() {
    if (count < 100) setCount(count + 1)
  }
  function subtract() {
    if (count > 0) setCount(count - 1)
  }

  // console.log("Script: Counter")

  return <>
    {/* {console.log("Render: Counter")} */}
    <div className="wrapper">
      <Button disabled={count === 0} fn={subtract} sign="-" />
      <div className="counters">
        {[...Array(props.recurse ? 1 : props.maxValue)].map((_, idx) =>
          <Gauge key={idx} value={count} max={props.maxValue} recurse={false} />)}
      </div>
      <Button disabled={count === 100} fn={add} sign="+" />
    </div >
  </>
};

// src/components/qwik/counter.tsx
/** @jsxImportSource @builder.io/qwik */
import { $, component$, useSignal, useStylesScoped$ } from '@builder.io/qwik'
import Button from './button'
import Gauge from './gauge'

export default component$((props: { initialValue: number, maxValue: number, recurse: boolean }) => {
  useStylesScoped$(/*scss*/`
    .wrapper {
      display: flex;
      flex-direction: row;
      align-items: center;
      justify-content: center;
      gap: 20px;
    }

    .counters:has(:global(.recurse)) {
      display:flex;
      align-items: center;
    }
  `)

  const count = useSignal(props.initialValue)
  const add = $(() => {
    if (count.value < 100) count.value++
  })
  const subtract = $(() => {
    if (count.value > 0) count.value--
  })

  //  console.log(`Script: Counter`) 

  return <>
    {/* {console.log(`Render: Counter`)} */}
    <div class="wrapper">
      <Button disabled={count.value === 0} fn={subtract} sign='-' />
      <div class="counters">
        {[...Array(props.recurse ? 1 : props.maxValue)].map((_, idx) =>
          <Gauge key={idx} value={count.value} max={props.maxValue} recurse={false} />)}
      </div>
      <Button disabled={count.value === 100} fn={add} sign='+' />
    </div>
  </>
})
